name: common_network_components
description: Shared network components
version: 0.0.2
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  common_models:
    path: ../common_models

dev_dependencies:
  test: ^1.16.0
