name: common_network_components
description: Shared network components
version: 0.0.7
publish_to: 'none'

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  dio: ^5.4.0
  meta: ^1.11.0
  common_models:
    git:
      url: https://github.com/kume1a/flutter_common.git
      path: packages/common_models

dev_dependencies:
  lint: ^2.3.0
