name: common_utilities
description: A starting point for Dart libraries or applications.
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  test: ^1.16.0

  lint: ^1.6.0
