name: flutter_common
description: Shared components, widgets and utility classes for applications
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  lint: ^1.5.3

dev_dependencies:
  test: ^1.16.0
