name: common_widgets
description: Shared widgets for flutter apps
version: 0.0.6
publish_to: 'none'

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  diffutil_dart: ^4.0.0

dev_dependencies:
  lint: ^2.2.0
