name: common_widgets
description: Shared widgets for flutter apps
version: 0.0.6
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  diffutil_dart: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  lint: ^1.7.2

flutter: