name: common_widgets
description: Shared widgets for flutter apps
version: 0.0.5
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: