name: common_models
description: shared model classes
version: 0.0.4
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  collection: ^1.17.1
  libphonenumber_plugin: ^0.3.2

dev_dependencies:
  lint: ^1.8.2
