name: common_models
description: shared model classes
version: 0.0.4
publish_to: 'none'

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  collection: ^1.17.1
  libphonenumber_plugin: ^0.3.3
  meta: ^1.10.0

dev_dependencies:
  lint: ^2.2.0
