name: common_models
description: Shared model classes
version: 0.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  freezed_annotation: ^0.14.3

dev_dependencies:
  test: ^1.16.0
  freezed: ^0.14.3
  build_runner: ^2.0.6

