name: common_models
description: Shared model classes
version: 0.0.4
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  freezed_annotation: ^1.0.0

dev_dependencies:
  test: ^1.16.0
  freezed: ^1.0.0
  build_runner: ^2.1.5
  lint: ^1.7.2

